[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/console"
  to = "/console.html"
  status = 200

[[redirects]]
  from = "/terminal"
  to = "/console.html"
  status = 200

[[redirects]]
  from = "/signals"
  to = "/signals.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
